name: insta_like_animation_flutter
description: "Insta like animation in flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/bridge.jpg
    - assets/airport.jpg
    - assets/food.jpg
    - assets/user_pic.jpg
    - assets/posts.json
